### ISSUE TITLE
Allow excluding issues from project board by archiving them

### ISSUE THREAD

**Issue by GiuliaTeggi** [nearform/github-action-add-issues-to-project#56]
We want to be able to exclude certain issues from the board so that they cannot be added back into it when running the action. This can be achieved by archiving the unwanted issues and then making the action filter out the issues marked as 'archived'.

This is what I found looking into how to possibly implement this. 

- For projects **beta** boards:  when running `get-issues` each issue can return the projects they belong to in the `projectNextItems` field and whether they have been archived in that project. Unfortunately there doesn't seem to be a way to return all (or any) archived issues in a project using the projects beta api.

![Capture](https://user-images.githubusercontent.com/30217557/158393026-5ced1190-8972-4e66-b3c7-9125a6fb13dc.PNG)

- For legacy projects boards, we can get all the existing projects cards with `getAllBoardIssues` and then filter out the new issues against the cards referencing them that have `isArchived` set to true.

![Capture](https://user-images.githubusercontent.com/30217557/158418122-15f2186c-9246-4683-bc18-338e1a4abd5d.PNG)

**Comment by simoneb** [comment]
good analysis, let's implement this and make sure that the docs contain instructions about archiving cards/issues in order to avoid them reappearing
